### ISSUE TITLE
Error in Laravel 4.2.17 - base64_decode() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by hmpmarketing** [mmanos/laravel-search#23]
Hi,

When I run the following line on my index:

$results = Search::index('acpdata')->search('campaign_id', 272)->get();

I get this error:

base64_decode() expects parameter 1 to be string, array given

Error is @ line 190 of file /vendor/mmanos/laravel-search/src/Mmanos/Search/Index/Elasticsearch.php

json_decode(base64_decode(array_get($hit, '_source._parameters', array())), true)

Help!

Regards

**Comment by hmpmarketing** [comment]
Is it fixed?

**Comment by mmanos** [comment]
Yes, it should be. I merged in the pull request from @dmyers.

**Comment by hmpmarketing** [comment]
Thanks! will test

**Comment by hmpmarketing** [comment]
@mmanos 

Still broken, new error on Line 191

Call:

$results = Search::index('acpdata')->search('campaign_id', 3789)->get();

{"error":{"type":"ErrorException","message":"array_merge(): Argument #2 is not an array","file":"\/Users
\/herickpaiva\/Desktop\/Git_Repos\/ACP2015\/acp2015\/vendor\/mmanos\/laravel-search\/src\/Mmanos\/Search
\/Index\/Elasticsearch.php","line":191}}

**Comment by dmyers** [comment]
The commits (including merge) needs to be cherry picked onto the L5 branch.

**Comment by hmpmarketing** [comment]
Sorry dont understand what that means. Error is coming up with Laravel 4.2

**Comment by dmyers** [comment]
@hmpmarketing Sorry about that, it only fixed half of the issue. There is a new update which has it all fixed.
